name: Publish Docker images
on:
  workflow_dispatch: {}
  schedule:
    - cron: "46 2 * * 1"

jobs:
  build-and-push:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: |
          for image in */Dockerfile; do
            image="$(basename $(dirname $image))"

            if ! test -f "$image/build.sh"; then
              echo "::error ::missing build.sh file at /$image"
              exit 1
            fi

            "$image/build.sh" ${{ secrets.DOCKERHUB_ORG }}
          done
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          for image in */Dockerfile; do
            image="$(basename $(dirname $image))"
            docker push "${{ secrets.DOCKERHUB_ORG }}/$image" --all-tags
          done
      - name: Update image READMEs
        env:
          DH_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DH_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          for image in */Dockerfile; do
            image="$(basename $(dirname $image))"

            if ! test -f "$image/README.md"; then
              echo "::warning ::missing README.md file at /$image"
              continue
            fi

            node .github/scripts/update-image-readme.js "${{ secrets.DOCKERHUB_ORG }}/$image" "$image/README.md"
          done
